version: 1
disable_existing_loggers: false
formatters:
  f_standard:
    format: "%(levelname)s|%(name)s|%(asctime)s: %(message)s"
handlers:
  h_stderr: 
    class: "logging.StreamHandler"
    formatter: "f_standard"
    level: "INFO"
    stream: "ext://sys.stderr"
  h_file:
    class: "logging.FileHandler"
    formatter: "f_standard"
    level: "DEBUG"
    filename: "/home/pi/liker.log"
loggers:
  luigi-interface: 
    level: "DEBUG"
    handlers: ["h_stderr", "h_file"]
  liker: 
    level: "DEBUG"
    handlers: ["h_stderr", "h_file"]

